DockCvm: better actions and output msg support

diff --git a/docker-cernvm b/docker-cernvm
--- a/docker-cernvm
+++ b/docker-cernvm
@@ -38,29 +38,29 @@ function pen() (
   echo -e -n "$@" >&2
 )
 
-# Successful echo. Echo 'ok' in green, or whatever you want if provided
+# Successful echo. Echo 'ok' in green, or whatever you want if provided.
 function pok() (
   local msg="$1"
   [[ $msg == '' ]] && msg='ok'
   pe "${Cg}${msg}${Cz}"
 )
 
-# Error echo. Echo 'error' in red, or whatever you want if provided
+# Error echo. Echo 'error' in red, or whatever you want if provided.
 function perr() (
   local msg="$1"
   [[ $msg == '' ]] && msg='error'
   pe "${Cr}${msg}${Cz}"
 )
 
-# Warning echo. Echo 'warning' in yellow, or whatever you want if provided
+# Warning echo. Echo 'warning' in yellow, or whatever you want if provided.
 function pwarn() (
   local msg="$1"
   [[ $msg == '' ]] && msg='error'
   pe "${Cy}${msg}${Cz}"
 )
 
-# Wrap a command, prints it on screen before executing it. Execute it for real
-# only if dry=0. Preserve its exit state.
+# Wrap a command, prints it on screen before executing it. Execute it for real only if dry=0.
+# Preserve its exit state.
 #
 # Usage: wrap [opts] <msg> <cmd> [param1 [param2 [param3...]]]
 function wrap() {
@@ -108,7 +108,7 @@ function wrap() {
     [[ $custom_ok == 0 ]] && pok
   elif [[ $non_fatal == 1 ]] ; then
     # Erred, but it was non-fatal
-    pwarn 'non-fatal'
+    pwarn 'failed (non-fatal)'
   else
     perr
 
@@ -167,22 +167,22 @@ function dcvm_register() (
   r=$?
 
   if [[ $r == 0 ]] ; then
-    image_id=$( wrap --out --custom-ok "Fetching Image ID for \"${tag}\"" dcvm_get_image_id "${tag}" )
+    image_id=$(wrap --out --custom-ok "Fetching Image ID for \"${tag}\"" dcvm_get_image_id "${tag}")
     r=$?
     if [[ $r == 0 ]] ; then
-      pok "${image_id}"
+      pok "${image_id:0:10}"
     fi
   fi
   return $r
 )
 
-# Attempt to unmount all bind mounts to CernVM, and the main repository. No args
-# are accepted.
+# Attempt to unmount all bind mounts to CernVM, and the main repository. No args are accepted. This
+# operation is likely to require root access
 function dcvm_unmount_all() (
 
   local err=0
 
-  # Go through all the bind mounts
+  # Unmount all bind mounts belonging to us
   exec 3< <( grep "^${cvm_root} " /etc/mtab | awk '{ print $2 }' )
   while read -u 3 bind_mount ; do
     wrap "Unmounting bind mount ${bind_mount}" umount "$bind_mount"
@@ -203,7 +203,7 @@ function dcvm_unmount_all() (
     fi
 
     if [[ $err == 0 ]] ; then
-      pe "${Cg}Everything unmounted.${Cz}"
+      pok 'Everything unmounted.'
       return 0
     fi
 
@@ -227,7 +227,7 @@ function dcvm_mount() (
   [[ $? == 0 ]] || return 1
 
   # Fetch the list of layers
-  layers=$( wrap --out "Fetching layers for ${image_id}" cat ${docker_prefix}/aufs/layers/${image_id} )
+  layers=$(wrap --out "Getting layers for ${image_id:0:10}" cat ${docker_prefix}/aufs/layers/${image_id})
   [[ $? == 0 ]] || return 1
 
   # Append our current image to the list of layers to inspect
@@ -257,26 +257,19 @@ function dcvm_mount() (
     r=1
   else
 
-
     if [[ $already_mounted == 1 ]] ; then
-
-      #pe "already bind-mounted: try to unmount it first (errors are non-fatal)"
-
       wrap --non-fatal \
-        "Found layer ${layer_id} already mounted: trying to unmount first" \
+        "Found layer ${layer_id:0:10} already mounted: trying to unmount first" \
         umount "$layer_path"
       if [[ $? == 0 ]] ; then
         # We have unmounted it successfully
         already_mounted=0
       fi
-
     fi
 
     # See again if now it is already mounted. If not, try to mount it. In this case, errors are
     # considered fatal
     if [[ $already_mounted == 0 ]] ; then
-
-      ### cvm ###
 
       # Check if the main mountpoint is mounted
       cvm_main_is_mounted=0
@@ -302,19 +295,17 @@ function dcvm_mount() (
         r=$?
       fi
 
-      ### /cvm ###
-
       if [[ $r == 0 ]] ; then
 
         wrap \
-          "Bind-mounting CernVM branch ${cvm_branch} over ${layer_id}" \
+          "Bind-mounting CernVM branch ${cvm_branch} over ${layer_id:0:10}" \
           mount --bind "$cvm_root" "$layer_path"
         r=$?
 
         if [[ $r == 0 ]] ; then
-          pe "Layer ${Cg}${layer_id}${Cz} freshly mounted."
+          pe "Layer ${Cg}${layer_id:0:10}${Cz} freshly mounted."
         else
-          pe "${Cr}Error:${Cz} cannot bind mount over ${Cr}${layer_id}${Cz}!"
+          pe "${Cr}Error:${Cz} cannot bind mount over ${Cr}${layer_id:0:10}${Cz}!"
         fi
 
       else
@@ -325,7 +316,7 @@ function dcvm_mount() (
 
     else
 
-      pe "Reusing existing layer mount ${Cy}${layer_id}${Cz}."
+      pe "Reusing existing layer mount ${Cy}${layer_id:0:10}${Cz}."
       r=0
 
     fi
@@ -333,7 +324,7 @@ function dcvm_mount() (
     if [[ $r == 0 ]] ; then
       # Info about CernVM snapshot in use
       cvm_snapshot=$( basename "$layer_path"/.installed_* | cut -d_ -f2 )
-      pe "CernVM snapshot in use: ${Cm}${cvm_snapshot}${Cz}."
+      pe "CernVM snapshot in use: ${Cm}${cvm_snapshot}${Cz}"
     fi
 
   fi
@@ -348,6 +339,7 @@ function main() (
   local tag
   local opts
   local r
+  local force_root=0
 
   while [[ $# -gt 0 ]] ; do
     case "${1}" in
@@ -359,6 +351,10 @@ function main() (
         opts="$2"
         shift 2
       ;;
+      --force-root)
+        force_root=1
+        shift
+      ;;
       *)
         break
       ;;
@@ -368,21 +364,34 @@ function main() (
   action="$1"
   shift
 
+  # Check options
+
   if [[ $action == register || $action == mount ]] ; then
     if [[ $tag == '' ]] ; then
       pe "Argument ${Cr}--tag${Cz} is mandatory."
-      r=1
-    else
-      dcvm_$action "$tag"
-      r=$?
+      return 1
     fi
+  fi
+
+  if [[ $action == unmount-all || $action == mount ]] ; then
+    if [[ $(whoami) != root && $force_root == 0 ]] ; then
+      pe "${Cr}${action}${Cz} is a root operation: cannot continue" \
+        "(force with ${Cr}--force-root${Cz})"
+      return 1
+    fi
+  fi
+
+  if [[ $action == register || $action == mount ]] ; then
+    dcvm_$action "$tag"
+    r=$?
   elif [[ $action == unmount-all ]] ; then
     dcvm_unmount_all
     r=$?
   else
     pe "Action unknown or unspecified: \"${Cr}${action}${Cz}\"."
-    pe "Usage: ${Cm}${prog}${Cz} [${Cc}--tag ${Cm}<tagname>${Cz}] [${Cc}--dry-run${Cz}] [${Cm}register${Cz}|${Cm}unmount-all${Cz}|${Cm}mount${Cz}]"
-    r=1
+    pe "Usage: ${Cm}${prog}${Cz} [${Cc}--tag ${Cm}<tagname>${Cz}] [${Cc}--dry-run${Cz}]" \
+      "[${Cc}--force-root${Cz}] [${Cm}register${Cz}|${Cm}unmount-all${Cz}|${Cm}mount${Cz}]"
+    return 1
   fi
 
   return $r
